installed phpUnit, beacuse we gonna use it for writing test
new2lagoon/dev.lagoon pull request #10
Opened 2019-02-26 14:33 UTC by dimaMikky

check it please

2019-02-26 14:46 UTC, new2lagoon commented
> check it please

i think it is great code . What do you think about it @ibudasov ?

2019-02-26 14:59 UTC, dimaMikky commented
> > check it please
> 
> i think it is great code . What do you think about it @ibudasov ?
> still waiting the response

2019-02-26 15:04 UTC, ibudasov requested changes

2019-02-26 15:04 UTC, ibudasov commented on README.md
> +2. installed PHPUnit, because we gonna use it for writing tests
NBC: is it some sort of a changelog?

2019-02-26 15:04 UTC, ibudasov commented on composer.json
> +        "symfony/phpunit-bridge": "^4.0",
I don't see the actual phpunit/phpunit, where is it?

2019-02-26 15:04 UTC, ibudasov commented on src/Controller/Calculator.php
> +}
You have installed and configured GrumPHP, right? 

It should block all the code:
- without typehints
- without return types
- no empty line at the end
- with commented out code
- no declare('strict_types=1');

All those things are bad and must be filtered out by robots.
Ping me if you need help with configuring it.

Also add all of this to the codestyle, please.

2019-02-26 15:04 UTC, ibudasov commented on tests/Controller/CalculatorTest.php
> +class CalculatorTest extends TestCase
Look, PHPUnit is actually here!

2019-02-26 15:04 UTC, ibudasov commented on tests/Controller/CalculatorTest.php
> +    public function testAdd()
Let's make the name more explanatory!

2019-02-26 15:04 UTC, ibudasov commented on tests/Controller/CalculatorTest.php
> +        // assert that your calculator added the numbers correctly!
You want to put such a comment in the assertion as a 3rd parameter

2019-02-26 15:15 UTC, dimaMikky commented on composer.json
> +        "symfony/phpunit-bridge": "^4.0",
According the symfony testing guide i use the phpunit-bridge. It wraps the original PHPUnit binary to provide additional features.

2019-02-26 15:16 UTC, dimaMikky commented on README.md
> +2. installed PHPUnit, because we gonna use it for writing tests
good mention, ill fix it

2019-02-26 15:21 UTC, ibudasov commented on README.md
> +2. installed PHPUnit, because we gonna use it for writing tests
nono I mean, if you want it here - np, I'm just asking what is it for?

2019-02-26 15:21 UTC, ibudasov commented on composer.json
> +        "symfony/phpunit-bridge": "^4.0",
oh ok, let it be then

2019-02-27 11:39 UTC, new2lagoon commented on README.md
> +2. installed PHPUnit, because we gonna use it for writing tests
i put some changes, can you see them ?

2019-02-27 11:40 UTC, dimaMikky commented on README.md
> +2. installed PHPUnit, because we gonna use it for writing tests
@ibudasov , i put some changes. Can you see it ?

2019-02-27 11:57 UTC, ibudasov commented on README.md
> +2. installed PHPUnit, because we gonna use it for writing tests
yep, I do, but I don't see the PR in the list of PRs to review anymore :(

2021-03-31 11:10 UTC, closed without merging